Switching from python to 3/3.9.11
  ERROR: Unable to locate a modulefile for '3/3.9.11'
2023-10-14 23:32:35.377184: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/zhome/77/8/118225/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/zhome/77/8/118225/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "train_score.py", line 790, in <module>
    trainxt(manifold=args.manifold,
  File "train_score.py", line 766, in trainxt
    score_matching.trainxt.train_s1(M=M,
  File "/zhome/77/8/118225/Desktop/smrdm/smrdm/jaxgeometry/statistics/score_matching/trainxt.py", line 156, in train_s1
    np.save(os.path.join(save_path, "loss_arrays.npy"), jnp.stack(loss))
  File "<__array_function__ internals>", line 200, in save
  File "/zhome/77/8/118225/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 518, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'scores/SPDN2/T/loss_arrays.npy'
terminate called without an active exception
/zhome/77/8/118225/.lsbatch/1697319135.18349355.shell: line 33:  4283 Aborted                 python3 train_score.py --manifold SPDN --N 2 --loss_type T --train_net s1 --max_T 0.1 --lr_rate 0.001 --epochs 50000 --x_samples 32 --t_samples 128 --repeats 8 --samples_per_batch 16 --dt_steps 1000 --save_step 10 --seed 2712
