Loaded dependency [python3/3.10.12]: gcc/11.4.0-binutils-2.40
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0

Switching from python3/3.8.2 to python3/3.10.12
  Loading requirement: gcc/11.4.0-binutils-2.40 sqlite3/3.42.0
2024-04-30 01:10:37.988411: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-30 01:10:37.988484: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-30 01:10:37.994927: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 296, in <module>
    train_score()
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 274, in train_score
    train_s1(M=M,
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 113, in train_s1
    new_state, loss_val = update(state, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 61, in update
    loss, gradients = value_and_grad(loss_fun)(state.params, state.state_val, rng_key, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 55, in loss_fun
    return loss_model(generator, s1_model, x0, xt, t, dW, dt)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 33, in vsm_s1fun
    divs = vmap(lambda x0, xt, chart, t: generator.M.div((xt, chart), 
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 33, in <lambda>
    divs = vmap(lambda x0, xt, chart, t: generator.M.div((xt, chart), 
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/manifolds/riemannian/metric.py", line 98, in <lambda>
    M.div = lambda x,X: jnp.trace(jacfwdx(X)(x))+.5*jnp.dot(X(x),gradx(M.logAbsDet)(x))
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/autodiff/tuple.py", line 41, in jacf
    return jacfwd(fxchart,argnums=0)(x[0],x[1],*args,**kwargs)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/autodiff/tuple.py", line 39, in fxchart
    return f((x,chart),*args,**kwargs)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 34, in <lambda>
    lambda x: generator.grad_local(x, s1_model(x0, x[1], t))))(x0,xts,chartts,t)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/generators.py", line 429, in grad_local
    x = self.update_coords(x)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/generators.py", line 415, in update_coords
    return (self.M.invF((Fx,chart)), Fx)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/manifolds/nEllipsoid.py", line 58, in invF_steographic
    Rinvx = jnp.linalg.solve(self.get_B(x[1]/self.params),x[0]/self.params)
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 260, in deferring_binary_op
    raise TypeError(f"unsupported operand type(s) for {opchar}: "
TypeError: unsupported operand type(s) for /: 'tuple' and 'ArrayImpl'
2024-04-30 01:11:09.203514: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
